version: 1.0.{build}
pull_requests:
  do_not_increment_build_number: true
skip_tags: true
image: Visual Studio 2017
configuration: Release
platform: Any CPU
build:
  parallel: true
  verbosity: normal
notifications:
- provider: Email
  to:
  - timothy.macharia@outlook.com
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: false
